Remove Kind from the groupref
existing testcase samples dont use kind. For example
TestAllInSeries/samples/membership-with-expiration-date uses
config/samples/resources/cloudidentitymembership/membership-with-expiration-date/cloudidentity_v1beta1_cloudidentitymembership.yaml

2025-02-15T01:04:49.0038402Z     samples.go:123: error creating resource: CloudIdentityMembership.cloudidentity.cnrm.cloud.google.com "cloudidentitymembership-sample-expirationdate" is invalid: [<nil>: Invalid value: "": "spec.groupRef" must validate one and only one schema (oneOf). Found none valid, spec.groupRef.kind: Required value]

* ran make resource-docs